name: Build Piano Booster

on: [push, pull_request]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: brew install qt@6 fluidsynth rtmidi cmake ftgl
        
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt@6)
          make -j4
          
      - name: Save Mac App
        uses: actions/upload-artifact@v4
        with:
          name: PianoBooster-Mac
          path: build/

  build-windows:
    runs-on: windows-2025
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Install Windows Dependencies via Vcpkg
        run: |
          vcpkg install qtbase fluidsynth rtmidi ftgl --triplet x64-windows
          
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
          
      - name: Save Windows App
        uses: actions/upload-artifact@v4
        with:
          name: PianoBooster-Windows
          path: build/Release/
